version: "3.7"

x-restart-policy: &restart_policy
  restart: unless-stopped

x-logging: &logging
  logging:
    driver: "json-file"
    options:
      max-size: "10m"
      max-file: "2"

x-healthcheck: &healthcheck
  interval: 30s
  start_period: 90s
  timeout: 20s
  retries: 3

services:
  rabbitmq:
    <<: [*restart_policy, *logging]
    image: rabbitmq:3.13-management-alpine
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=mypass
    expose:
      - 5672
      - 15672
      - 15692
    ports:
      - 5672:5672
      - 15672:15672
      - 15692:15692
    volumes:
      - app-rabbitmq-data:/var/lib/rabbitmq/mnesia/
    healthcheck:
      <<: *healthcheck
      test: ["CMD-SHELL", "rabbitmq-diagnostics -q ping"]

volumes:
  app-rabbitmq-data:
